language: ruby
rvm:
  - 2.3.0
script:
  - true
deploy:
  provider: heroku
  app:
    master: radbot-production
  api_key:
    secure: whewQid344GnZymZaUo/ZigDcpMKkI8pS8OY23auUGomiZ5xJ3zr9BAPDoChCbgSbhH2NFR9+CMW3iTdVXQeIiPdA3b83SmABXlgA1muqsV+swq97vYnAPbwlXPFsK5h9gELE0cHH33WFN/xoXW757aRD23l2HjV+Ehf5X0ZoCzgKIa0bzlq23WqOttJP8NtsM2s3rPJ4yd6jw/WufmO3NZfpm2sloU8eQBr0tv2lQg0tGm+h0rOZqkociGJIMCnCvj6u5vTt0Vo1Mze2IsO2c/NIgMllNqL9gfHLN5s2FSJ+aav0YfoFvSgY6BrcbX1ZHWH3g0XRaXhX8vmc3jwOUnP9VwimBvITZ7kKF6hX13R+87fvq7R/KGQKVB7lHpWrqxUiD29vP8B1qw+zMWL55BDxXSPZqAu/99540UYPlof9bF+CZW9cuxBHJqVBHHjGD74vTd4Xf1x7/ogdC34yqUVFcZOe4X/XZhj7ZRB39jeQZ8wHVpmNTqhtth1PnMC7ycza1LREpXtRQ4rUB+fme0s9NGg7xEz8J/2WlHVcI7ysbCCcOUt5rVAB9ExD8VTSkgpMOKSIoVxCQFNentp2/O7Fa/N+T+r2eiZ8JjJn21QAIy22n+K/z6DeFn1YyDSflisn+BIo89HaSBAGZMqzFHc9O+ER4jWsBNB31lC0y4=
