source "https://rubygems.org"

gem "byebug"

gem "lita"
gem "lita-aww"
gem "lita-catgif"
gem "lita-cleverbot"
gem "lita-dotenv"
gem "lita-down-for-everyone"
gem "lita-github-pinger"
gem "lita-hangout", github: "csexton/lita-hangout"
#gem "lita-hangout", path: "~/src/lita-hangout"
#gem "lita-squirrel", path: "~/src/lita-squirrel"
gem "lita-imgflip"
gem "lita-karma"
gem "lita-slack"
gem "lita-wtf"
